version: "3.7"
services:
    payara:
        container_name: payara
        build: 
            context: .
            dockerfile: ./docker/images/payara/Dockerfile
        ports: 
            - "8080:8080"
            - "8181:8181"
            - "4848:4848"
        environment:
            DEPLOY_PROPS: --properties=force=true
    postgres:
        container_name: postgres
        build: ./docker/images/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: dev_password_1508
        