version: "3.7"
services:
    glassfish:
        container_name: glassfish
        build: ./docker/images/glassfish
        ports:
            - "8080:8080"
            - "4848:4848"
        volumes:
            - ./target/generated-builded-files:/opt/glassfish5/glassfish/domains/domain1/autodeploy/
    postgres:
        container_name: postgres
        build: ./docker/images/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: dev_password_1508
        volumes:
            - ./docker/images/postgres/install.sql:/docker-entrypoint-initdb.d/
            - ./data/postgres:/var/lib/postgresql/data
        